sudo apt update;
sudo apt upgrade;
sudo apt install git;
sudo apt install hugo=0.92.2;
mkdir hugoServer;
hugo new site hugoServer/mycv;
git clone https://gitlab.com/mertbakir/resume-a4.git hugoServer/mycv/themes/resume-a4;
cp hugoServer/mycv/themes/resume-a4/config.yaml hugoServer/mycv/;
cp -r hugoServer/mycv/themes/resume-a4/exampleSite/data hugoServer/mycv/;
rm hugoServer/mycv/config.toml;
hugo --source hugoServer/mycv -D;
